### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: ByteArray with size 118 is bigger than allowed 3

### ISSUE THREAD

**Issue by Apricityx** [MiraculixxT/bluemap-marker#12]
When a player tries joining the server,they can only recive a message like this.

BMM version:bmm-fabric-1.5.0
Bluemap version:BlueMap-3.16-fabric-1.20
Minecraft version:1.20.1
fabricloader version:0.4.22
fabricAPI verion:fabric-api-0.87.0+1.20.1

latest.log followed below.

[latest.log](https://github.com/MiraculixxT/bluemap-marker/files/12337624/latest.log)

**Comment by MiraculixxT** [comment]
Hey, it seems to be an compatibility issue with silk and an other mod. This was discovered by a user before and he made a custom version of Silk [(here)](https://cdn.discordapp.com/attachments/863844716047106068/1135936844794708028/silk-all-1.10.1.jar) that *could* fix this issue

**Comment by Apricityx** [comment]
> Hey, it seems to be an compatibility issue with silk and an other mod. This was discovered by a user before and he made a custom version of Silk [(here)](https://cdn.discordapp.com/attachments/863844716047106068/1135936844794708028/silk-all-1.10.1.jar) that *could* fix this issue

Thank you.
But i just installed bluemap,silk,fabricapiandkotlin,which are essential to load BMM.
I will try your suggestion later.
btw,your mod is excellent,we do love it :D.
