### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by jurohn** [MiraculixxT/bluemap-marker#18]
17.12 11:49:01 [Server] INFO [BlueMap-Marker] Loading server plugin BlueMap-Marker v160
17.12 11:49:01 [Server] ERROR [BlueMap-Marker] Error initializing plugin 'bmm-paper-1.6.1.jar' in folder 'plugins' (Is it up to date?)
17.12 11:49:01 [Server] INFO dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.20.4

**Comment by jurohn** [comment]
17.12 11:49:04 [Server] ERROR Error occurred while enabling BlueMap-Marker v160 (Is it up to date?)
17.12 11:49:04 [Server] INFO java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
17.12 11:49:04 [Server] INFO at dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:169) ~[?:?]
17.12 11:49:04 [Server] INFO at dev.jorel.commandapi.CommandAPI.onEnable(CommandAPI.java:135) ~[?:?]
17.12 11:49:04 [Server] INFO at de.miraculixx.bmm.BMMarker.onEnable(BMMarker.kt:34) ~[bmm-paper-1.6.1.jar:?]
17.12 11:49:04 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
17.12 11:49:04 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
17.12 11:49:04 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
17.12 11:49:04 [Server] INFO [BlueMap-Marker] Disabling BlueMap-Marker v160
17.12 11:49:04 [Server] ERROR Error occurred while disabling BlueMap-Marker v160
17.12 11:49:04 [Server] INFO kotlin.UninitializedPropertyAccessException: lateinit property blueMapInstance has not been initialized
17.12 11:49:04 [Server] INFO at de.miraculixx.bmm.BMMarker.onDisable(BMMarker.kt:38) ~[bmm-paper-1.6.1.jar:?]
17.12 11:49:04 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
17.12 11:49:04 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
17.12 11:49:04 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
17.12 11:49:04 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-330]
17.12 11:49:04 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by jurohn** [comment]
@MiraculixxT is this expected? Seems like it refers to version 1.60 on some lines.

**Comment by MiraculixxT** [comment]
The issue comes from a library i use that seems to be not compatible with Minecraft 1.20.4. I'm sorry for that, i got baited by their update logs and added the wrong version. Will update it now

**Comment by MiraculixxT** [comment]
Should be fixed now :)

**Comment by jurohn** [comment]
@MiraculixxT did you push it to modrinth already or do i only see the old version? Im not good in compiling projects from git

**Comment by xTreeTV** [comment]
@jurohn I think it was just replaced. Try to redownload the 1.6.1 from modrinth.

**Comment by jurohn** [comment]
@xTreeTV still the same

**Comment by MiraculixxT** [comment]
I replaced the version jar in Modrinth to avoid having a broken version online. Sometimes your browser caches the old version because its the same download link so it reuses the old one. 

I will upload a clean new version later today due #17 merge, so you can use this instead if the error persists.

(And yes, i forgot to push)

**Comment by jurohn** [comment]
@MiraculixxT Thank you, great response time and help!

**Comment by jurohn** [comment]
@MiraculixxT Is the new one on already? I still see the old one i guess

**Comment by DarkSpir** [comment]
On modrinth the plugin version is 1.6.2 for Paper but still 1.6.0 for Fabric. I see in the source that Fabric was also bumped to 1.6.2. Can you please re-check this?
