### ISSUE TITLE
Console notification

### ISSUE THREAD

**Issue by jurohn** [MiraculixxT/bluemap-marker#20]
Are you aware of this line in the console:

23.12 18:57:10 [Server] INFO BMM >> You are running a beta version. Bugs may appear!

Is isnt in beta anymore right?

**Comment by DlljsCodes** [comment]
I'm also experiencing this issue on BMM 1.6.3 Paper

**Comment by MiraculixxT** [comment]
Fixed version lookup & updater in the newest commit on `dev/2.0`
