### ISSUE TITLE
Modrinth plugin version is still 1.6.0 for Fabric

### ISSUE THREAD

**Issue by DarkSpir** [MiraculixxT/bluemap-marker#21]
In #18 the bluemap-marker plugin has been updated to 1.6.2 handling Minecraft server version 1.20.4. On modrinth I see that release but only for the Paper API. Fabric still has the old release 1.6.0. Can you please re-check this?

**Comment by MiraculixxT** [comment]
At the point of publishing, a required library (adventure) wasn't fully updated for 1.20.4 cause of a lot internal changes (again... Mojang love to change things lately). 
But thanks for remembering me about updating it now! I completely forgot about it...

Here is the latest download for fabric now: https://modrinth.com/plugin/bmarker/version/1.6.2-fabric
