### ISSUE TITLE
1.20.6 error

### ISSUE THREAD

**Issue by jurohn** [MiraculixxT/bluemap-marker#26]
```
14.05 09:57:57 [Server] ERROR [BlueMap-Marker] Error initializing plugin 'bmm-paper-1.6.4-paper-all.jar' in folder 'plugins' (Is it up to date?)
14.05 09:57:57 [Server] INFO java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.commands.Commands vanillaCommandDispatcher'
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.nms.NMS_Common.getBrigadierDispatcher(NMS_Common.java:353) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandAPIBukkit.registerCommandNode(CommandAPIBukkit.java:641) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:664) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.AbstractCommandAPICommand.register(AbstractCommandAPICommand.java:307) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:60) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.Execution.register(Execution.java:38) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.AbstractCommandTree.register(AbstractCommandTree.java:66) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandTree.register(CommandTree.java:32) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.ExecutableCommand.register(ExecutableCommand.java:236) ~[?:?]
14.05 09:57:57 [Server] INFO at bmm-paper-1.6.4-paper-all.jar/de.miraculixx.bmm.MarkerCommand.<init>(MarkerCommand.kt:449) ~[bmm-paper-1.6.4-paper-all.jar:?]
14.05 09:57:57 [Server] INFO at bmm-paper-1.6.4-paper-all.jar/de.miraculixx.bmm.BMMarker.onLoad(BMMarker.kt:26) ~[bmm-paper-1.6.4-paper-all.jar:?]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:515) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by jurohn** [comment]
@MiraculixxT

**Comment by Zoriot** [comment]
@jurohn will be fixed with #27

**Comment by jurohn** [comment]
> @jurohn will be fixed with #27

18.05 22:53:58 [Server] WARN [BlueMap-Marker] Loading Paper plugin in the legacy plugin loading logic. This is not recommended and may introduce some differences into load order. It's highly recommended you move away from this if you are wanting to use Paper plugins.

**Comment by Zoriot** [comment]
Are you sure that you don’t have the JVM Flag:
`-Dpaper.useLegacyPluginLoading` enabled?
Please provide you startup command here.

**Comment by jurohn** [comment]
> Are you sure that you don’t have the JVM Flag: `-Dpaper.useLegacyPluginLoading` enabled? Please provide you startup command here.

I use Aikair flags. Thats what my control panel says (apex hosting)

**Comment by Zoriot** [comment]
> > Are you sure that you don’t have the JVM Flag: `-Dpaper.useLegacyPluginLoading` enabled? Please provide you startup command here.
> 
> I use Aikair flags. Thats what my control panel says (apex hosting)

Yea I`m pretty sure your Hosting Provider also adds ``-Dpaper.useLegacyPluginLoading=true``, why you get this warning. The Plugin works fine with that & also we cannot do anything about it. It`s just recommended to not use LegacyPluginLoading. 
Also maybe we use the Bukkit Plugin Loading System in the Final release, like it was before, thats up to MiraculixxT if we wait for the CommandAPI release.

**Comment by MiraculixxT** [comment]
Hey, i'm currently working on a rewrite in the `dev/2.0` branch. To support all version, the core library of CommandAPI needs to be shaded (and relocated) to take effect of the remapping. This also allows using the Snapshot version to fix the latest paper merge. 

>  It's highly recommended you move away from this if you are wanting to use Paper plugins.
They also work on a dedicated paper only release, but in the terms of how paper currently works it's impossible to do it differently. In the future, where everyone is updated to 1.20.5 we can just use the mapped versions and kill all pre support

**Comment by MiraculixxT** [comment]
Fixed beta version available now on modrinth
