### ISSUE TITLE
Editing shape edges

### ISSUE THREAD

**Issue by DlljsCodes** [MiraculixxT/bluemap-marker#28]
How do you edit the point coordinates of a shape marker after it has been defined? It's not possible in-game; you can only add new points. I tried editing the `.json` file inside `/plugins/BlueMap-Marker/marker` but they don't update on the BlueMap.

**Comment by MiraculixxT** [comment]
Hey, currently the editor does not allow removing/editing already added edges or positions. If you edit the json config, make sure to shut down the server first.

In a few days, i'll release a 2.0 version that will allow editing the list

**Comment by DlljsCodes** [comment]
Stopping and starting the server worked as an (albeit inelegant) workaround. Thanks for the update; will be looking forward to it.

**Comment by MiraculixxT** [comment]
A Beta version is now available on modrinth. The only downside, i use a completly new system to save markers now to allow for templates and more, so you need to readd all markers on updating

**Comment by DlljsCodes** [comment]
Is there an easy way to migrate my marker sets without manually readding them? Perhaps by editing the marker set files?

**Comment by MiraculixxT** [comment]
Currently, there is no easier way to convert them then just making new ones. Maybe once the 2.0 version is out of beta, there will be a convertor but no guarantee (this project consumed already a lot of my currently not much free time)

**Comment by MiraculixxT** [comment]
Convertor for old markers added! Enter `/bsettings convertor oldBMarkers` to convert all markers into the new format. You can delete the old BlueMap-Marker folder afterward.

Release later today

**Comment by DlljsCodes** [comment]
> Release later today

I can't find the new release on Modrinth, unless [this](https://modrinth.com/plugin/bmarker/version/2.0.0) was updated.

**Comment by MiraculixxT** [comment]
Sorry for the waiting, i was unsure if waiting for 1.21 would be better. But here you go!
[modrinth.com/plugin/bmarker/version/Wva5lSbv](https://modrinth.com/plugin/bmarker/version/Wva5lSbv)
