### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by jurohn** [MiraculixxT/bluemap-marker#29]
The 2.0 version is 10 times the size of the old version.
The changelog doesnt contain any text.

Please update us.

**Comment by MiraculixxT** [comment]
The addon was completely rewritten and nearly everything changed. You can look inside the repo Wiki to see all new features. Some affect a better and userfriendly Design and ui, but mostly the new owner system of markers changes current markers. Players with the base permission now have limited access to create their own markers without being able to modify others.

Also templates are a huge new addition, which is too much for a small message here (see wiki).

In addition for the file size, two libraries are now shaded into the plugin to allow full version support of 1.20.5+

**Comment by MiraculixxT** [comment]
The code currently sits in the dev/2.0 branch and will be merged into main as soon as i'm sure that no breaking bugs are inside

**Comment by jurohn** [comment]
> The addon was completely rewritten and nearly everything changed. You can look inside the repo Wiki to see all new features. Some affect a better and userfriendly Design and ui, but mostly the new owner system of markers changes current markers. Players with the base permission now have limited access to create their own markers without being able to modify others.
> 
> Also templates are a huge new addition, which is too much for a small message here (see wiki).
> 
> In addition for the file size, two libraries are now shaded into the plugin to allow full version support of 1.20.5+

Thank you for the awnser.
