### ISSUE TITLE
Request: Add git tags

### ISSUE THREAD

**Issue by impact112** [MiraculixxT/bluemap-marker#31]
Hello!
It would be nice if this repository gets tagged releases that correspond to Modrinth releases.

**Comment by MiraculixxT** [comment]
I prefer that users download it via Modrinth, so I can see how many users are still interested in the project (via download counts) and if it is worth to continue developing. 
If there should be a good reason to add releases here too, I would add them anyway :)

**Comment by impact112** [comment]
> I prefer that users download it via Modrinth, so I can see how many users are still interested in the project (via download counts) and if it is worth to continue developing. 
> If there should be a good reason to add releases here too, I would add them anyway :)

Git tags aren't the same thing as GitHub releases, they are only "pointers" to a commit that contain a message. Having tags helps with keeping track of versions of the source code and means that users can reproduce the modrinth builds.

**Comment by MiraculixxT** [comment]
Ah, that makes sense. I'll try to work me in with that for further releases. Thanks for letting me know!
