### ISSUE TITLE
Server operators not allowed unlimited marker sets and markers by default

### ISSUE THREAD

**Issue by zboggert** [MiraculixxT/bluemap-marker#35]
I recently installed Bluemap and Bmarker for fabric 1.21, and have run into the issue that server operators are held to the same limitations that regular players are held to unless one goes through the process of setting up permissions to bypass this using a permissions mod such as luckperms

**Comment by MiraculixxT** [comment]
Thanks for the report! I'll try to fix this in the next version, i thought the luckperms api would work like on paper

**Comment by MiraculixxT** [comment]
Fixed in newest build
