### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by jurohn** [MiraculixxT/bluemap-marker#36]
28.06 12:23:51 [Server] WARN [BlueMap-Marker] Loading Paper plugin in the legacy plugin loading logic. This is not recommended and may introduce some differences into load order. It's highly recommended you move away from this if you are wanting to use Paper plugins.

Is this gonna be fixed later? :)

**Comment by MiraculixxT** [comment]
I'm unsure which version of paper you use. BMaker still uses the recommend way for plugin descriptions. Paper introduced a new description type which is still marked as experimental and not recommend to use, unless the plugin uses features that require it

**Comment by jurohn** [comment]
Newest dev version of paper 1.21. Build 38
