### ISSUE TITLE
TP to a marker

### ISSUE THREAD

**Issue by rohoal1012** [MiraculixxT/bluemap-marker#41]
Make an option to tp inside the game to a marker created plsssss

**Comment by MiraculixxT** [comment]
Sure, i can add it onto my TODO list. But it will only have one permission, for waypoints i would suggest other methods

**Comment by joshbarbee** [comment]
Just expressing that this is a feature I want also, and would be extremely grateful if you can figure it out. I want players to be able to TP to the POIs I have defined on the map, but not TP anywhere they want. Kinda like fast traveling in games like Fallout.

**Comment by MiraculixxT** [comment]
What about an option inside the marker builder that is a true/false value if teleporting to that marker is allowed? If the value is false, only admins can teleport to that marker. Defaulting to false for all existing and new markers

**Comment by MiraculixxT** [comment]
Implemented in new 2.1.6 release
Download: https://modrinth.com/plugin/bmarker/versions
