### ISSUE TITLE
Make or indicate the marker "name" unique when using a template

### ISSUE THREAD

**Issue by Pwassoncru** [MiraculixxT/bluemap-marker#42]
`/<id> mark teleporters_poi teleporter`
`/<id> mark teleporters_poi teleporter`

The second line will override the first marker. This is not intuitive in the command line and should be indicated, For example, ```[Unique Name]``` instead of ```[Name]```.

A better solution would be to help the user making it unique, by for example adding the rounded location in the name, as this name is only used to mark and unmark a location. My marker will become ```teleporter_X50_Y72_Z45```.

**Comment by MiraculixxT** [comment]
I agree, overriding is probably a bad thing to do.
What do you think about giving a warning when the second command is entered, like "Hey, this name already exists. Override it by entering the command again or name it like 'teleporter_2'"?

**Comment by Pwassoncru** [comment]
That would work too. My suggestion with the current location was also to make it possible to identify from the map. When you want to unmark a marker, you usually don't know what his unique ID is. You could also have an additional command that lists the markers wth additional info (location, type, ..)

`/<id> list teleporters_poi`

**Comment by MiraculixxT** [comment]
I feel like adding a separate command that just lists everything can be quite overwhelming or even annoying for most users, but maybe my thought is wrong.

What I could think of as a more user-friendly way of distributing this information would be in the tab complete directly
![grafik](https://github.com/user-attachments/assets/9967ae1e-e6b3-43e8-ad5f-18f83d349cb3)

If you say the list command is still beneficial, i could also add it

**Comment by Pwassoncru** [comment]
I think the picture you sent is a good idea

**Comment by MiraculixxT** [comment]
Implemented in new 2.1.6 release
Download: https://modrinth.com/plugin/bmarker/versions
